### ISSUE TITLE
Needs response to the Linux patching controversy

### ISSUE THREAD

**Issue by ysangkok** [adityapakki/adityapakki.github.io#1]
I went to this website in search of your response to [the outrage](https://news.ycombinator.com/item?id=26889677), but it seems like there is no content on it. I'd like to hear your thoughts on research ethics and the university's interactions with you. Thanks!

**Comment by silverkorn** [comment]
https://www-users.cs.umn.edu/~kjlu/papers/clarifications-hc.pdf ?

**Comment by G2G2G2G** [comment]
https://cse.umn.edu/cs/statement-cse-linux-kernel-research-april-21-2021
lmao

**Comment by psociety** [comment]
I'm leaving here Aditya Pakki's message trying to play the victim while still being an asshole/douchebag:
On Wed, Apr 21, 2021 at 02:56:27AM -0500, Aditya Pakki wrote:
> Greg,
> 
> I respectfully ask you to cease and desist from making wild accusations
> that are bordering on slander.
> 
> These patches were sent as part of a new static analyzer that I wrote and
> it's sensitivity is obviously not great. I sent patches on the hopes to get
> feedback. We are not experts in the linux kernel and repeatedly making
> these statements is disgusting to hear.
> 
> Obviously, it is a wrong step but your preconceived biases are so strong
> that you make allegations without merit nor give us any benefit of doubt.
> 
> I will not be sending any more patches due to the attitude that is not only
> unwelcome but also intimidating to newbies and non experts.

https://lore.kernel.org/linux-nfs/YH%2FfM%2FTsbmcZzwnX@kroah.com/

**Comment by dustinlw1987** [comment]
What a fucking dickgobbler.

**Comment by dustinlw1987** [comment]
Wanker hasn't responded to anything. He knows he is completely in the wrong.

**Comment by ysangkok** [comment]
Seems like there won't be a response so I'll just close this so that it doesn't clutter.
